DROP TABLE IF EXISTS IDTable;


CREATE TABLE IDTable(
    userId SERIAL PRIMARY KEY,
    firstName VARCHAR(50) NOT NULL,
    lastName VARCHAR(50) NOT NULL,
    userRole VARCHAR(15) NOT NULL,
    hobby VARCHAR(250) NOT NULL,
    bio VARCHAR(2000) NOT NULL,
    favNum INTEGER NOT NULL
);