import requests


post_data = {
    "firstName": "Jotaro",
    "lastName": "Star",
    "hobby": "ORAORAORAORAORAOROARAORAORAORAORAOROA",
    "bio": "ORAORAORAORAORAOROARAORAORAORAORAOROAORAORAORAORAORAOROARAORAORAORAORAOROAORAORAORAORAORAOROARAORAORAORAORAOROAORAORAORAORAORAOROARAORAORAORAORAOROAORAORAORAORAORAOROARAORAORAORAORAOROA",
    "favNum": 69
}

res = requests.post('http://127.0.0.1:5000/create_user', json=post_data)
if res.ok:
    print(res.json())